/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistem;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Capital
 */
public class AdminSis extends javax.swing.JFrame {
    public String URL;
    /**
     * Creates new form AdminSis
     */
    public AdminSis() {
        initComponents();
        this.setLocationRelativeTo(null);
        LogConexion tyu = new LogConexion();
        tyu.open();
        int id = tyu.getAlId();
        jLabel50.setText(""+id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        controlPane = new javax.swing.JTabbedPane();
        userCtrl = new javax.swing.JPanel();
        muser_button = new javax.swing.JTabbedPane();
        createUTAb = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cusernameField = new javax.swing.JTextField();
        cpasswordField = new javax.swing.JTextField();
        cprivilegeCombo = new javax.swing.JComboBox<>();
        cusr_button = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        showNextID = new javax.swing.JLabel();
        user_etiqueta = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        cnamefield = new javax.swing.JTextField();
        modifyUTab = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        user_search_field = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        u_res_1 = new javax.swing.JTextField();
        u_res_2 = new javax.swing.JTextField();
        u_res_3 = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        u_res_4 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        eraseUTab = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        u_search_field = new javax.swing.JTextField();
        usrLb = new javax.swing.JLabel();
        privilegeLb = new javax.swing.JLabel();
        euser_button = new javax.swing.JButton();
        u_lb_1 = new javax.swing.JLabel();
        u_lb_2 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        regCtrl = new javax.swing.JPanel();
        registerPane = new javax.swing.JTabbedPane();
        modifyRTab = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        upfield = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        f1 = new javax.swing.JTextField();
        f2 = new javax.swing.JTextField();
        f3 = new javax.swing.JTextField();
        f4 = new javax.swing.JTextField();
        f12 = new javax.swing.JTextField();
        f13 = new javax.swing.JTextField();
        f14 = new javax.swing.JTextField();
        f15 = new javax.swing.JTextField();
        f16 = new javax.swing.JTextField();
        f17 = new javax.swing.JTextField();
        f18 = new javax.swing.JTextField();
        f20 = new javax.swing.JTextField();
        f21 = new javax.swing.JTextField();
        f7 = new javax.swing.JTextField();
        f8 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        f9 = new javax.swing.JTextField();
        f10 = new javax.swing.JTextField();
        f11 = new javax.swing.JTextField();
        f5 = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        f6 = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        f19 = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        eraseRTab = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        delRegField = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jLabel55 = new javax.swing.JLabel();
        alarmCtrl = new javax.swing.JPanel();
        alarmPane = new javax.swing.JTabbedPane();
        createATab = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        alarmIDLb = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        a1 = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        a2 = new javax.swing.JTextField();
        a3 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jLabel50 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        a4 = new javax.swing.JTextField();
        eraseATab = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        lookAlarm = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        al1 = new javax.swing.JLabel();
        al2 = new javax.swing.JLabel();
        al3 = new javax.swing.JLabel();
        al4 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jLabel57 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("System Administrator");

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        jLabel3.setText("Privileges");

        cusernameField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        cusernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusernameFieldActionPerformed(evt);
            }
        });

        cprivilegeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Production ", "Quality", "Administrator" }));
        cprivilegeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cprivilegeComboActionPerformed(evt);
            }
        });

        cusr_button.setText("Create");
        cusr_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusr_buttonActionPerformed(evt);
            }
        });

        jLabel5.setText("ID");

        user_etiqueta.setText("-");

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/logo.png"))); // NOI18N

        jLabel47.setText("Name");

        javax.swing.GroupLayout createUTAbLayout = new javax.swing.GroupLayout(createUTAb);
        createUTAb.setLayout(createUTAbLayout);
        createUTAbLayout.setHorizontalGroup(
            createUTAbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createUTAbLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel51)
                .addContainerGap())
            .addGroup(createUTAbLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(createUTAbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addGroup(createUTAbLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(createUTAbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)))
                    .addComponent(jLabel47))
                .addGap(46, 46, 46)
                .addGroup(createUTAbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createUTAbLayout.createSequentialGroup()
                        .addComponent(showNextID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(user_etiqueta)
                        .addGap(279, 279, 279))
                    .addGroup(createUTAbLayout.createSequentialGroup()
                        .addGroup(createUTAbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cnamefield, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(createUTAbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(createUTAbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cusernameField)
                                    .addComponent(cpasswordField)
                                    .addComponent(cprivilegeCombo, 0, 206, Short.MAX_VALUE))
                                .addComponent(cusr_button, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        createUTAbLayout.setVerticalGroup(
            createUTAbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createUTAbLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(createUTAbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(showNextID)
                    .addComponent(user_etiqueta))
                .addGap(38, 38, 38)
                .addGroup(createUTAbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cusernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(33, 33, 33)
                .addGroup(createUTAbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(cnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(createUTAbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cpasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(createUTAbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cprivilegeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(29, 29, 29)
                .addComponent(cusr_button)
                .addGap(30, 30, 30)
                .addComponent(jLabel51)
                .addGap(26, 26, 26))
        );

        muser_button.addTab("Create User", null, createUTAb, "");

        jLabel6.setText("ID");

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setText("User name");

        jLabel8.setText("Password");

        jLabel9.setText("Privileges");

        jButton3.setText("Modify");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        u_res_1.setBackground(new java.awt.Color(204, 204, 204));
        u_res_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u_res_1ActionPerformed(evt);
            }
        });

        u_res_2.setBackground(new java.awt.Color(204, 204, 204));

        u_res_3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/logo.png"))); // NOI18N

        u_res_4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel48.setText("Name");

        javax.swing.GroupLayout modifyUTabLayout = new javax.swing.GroupLayout(modifyUTab);
        modifyUTab.setLayout(modifyUTabLayout);
        modifyUTabLayout.setHorizontalGroup(
            modifyUTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modifyUTabLayout.createSequentialGroup()
                .addGroup(modifyUTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modifyUTabLayout.createSequentialGroup()
                        .addGroup(modifyUTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(modifyUTabLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel6)
                                .addGap(58, 58, 58))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modifyUTabLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(modifyUTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel48)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)))
                        .addGroup(modifyUTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(u_res_1)
                            .addComponent(u_res_2)
                            .addComponent(u_res_3, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(u_res_4)
                            .addComponent(user_search_field))
                        .addGap(25, 25, 25)
                        .addComponent(jButton2)
                        .addGap(0, 47, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modifyUTabLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel52)))
                .addContainerGap())
        );
        modifyUTabLayout.setVerticalGroup(
            modifyUTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modifyUTabLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(modifyUTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user_search_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jButton2))
                .addGap(50, 50, 50)
                .addGroup(modifyUTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(u_res_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(modifyUTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(u_res_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel48))
                .addGap(21, 21, 21)
                .addGroup(modifyUTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(u_res_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(modifyUTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(u_res_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(38, 38, 38)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        muser_button.addTab("Modify User", null, modifyUTab, "");

        jLabel10.setText("ID");

        jLabel11.setText("User");

        jLabel12.setText("Rol");

        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        euser_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        euser_button.setText("Erase");
        euser_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                euser_buttonActionPerformed(evt);
            }
        });

        u_lb_1.setText("-");

        u_lb_2.setText("-");

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/logo.png"))); // NOI18N

        javax.swing.GroupLayout eraseUTabLayout = new javax.swing.GroupLayout(eraseUTab);
        eraseUTab.setLayout(eraseUTabLayout);
        eraseUTabLayout.setHorizontalGroup(
            eraseUTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eraseUTabLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(eraseUTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(eraseUTabLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(eraseUTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(eraseUTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel11)
                                .addGroup(eraseUTabLayout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(eraseUTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(privilegeLb)
                                        .addComponent(usrLb))))
                            .addGroup(eraseUTabLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(euser_button)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eraseUTabLayout.createSequentialGroup()
                        .addGroup(eraseUTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(eraseUTabLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(u_search_field, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addGroup(eraseUTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addGroup(eraseUTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(u_lb_2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                                .addComponent(u_lb_1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(92, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eraseUTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel53)
                .addContainerGap())
        );
        eraseUTabLayout.setVerticalGroup(
            eraseUTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eraseUTabLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(eraseUTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(u_search_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(56, 56, 56)
                .addGroup(eraseUTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(u_lb_1))
                .addGap(23, 23, 23)
                .addGroup(eraseUTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usrLb)
                    .addGroup(eraseUTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(u_lb_2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(privilegeLb)
                .addGap(35, 35, 35)
                .addComponent(euser_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(jLabel53)
                .addGap(27, 27, 27))
        );

        muser_button.addTab("Erase User", eraseUTab);

        javax.swing.GroupLayout userCtrlLayout = new javax.swing.GroupLayout(userCtrl);
        userCtrl.setLayout(userCtrlLayout);
        userCtrlLayout.setHorizontalGroup(
            userCtrlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(muser_button)
        );
        userCtrlLayout.setVerticalGroup(
            userCtrlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(muser_button)
        );

        muser_button.getAccessibleContext().setAccessibleName("Crear U");
        muser_button.getAccessibleContext().setAccessibleDescription("");

        controlPane.addTab("User Control", userCtrl);

        jLabel13.setText("ID");

        jButton6.setText("Search");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel14.setText("Fecha Analisis");

        jLabel15.setText("Clave");

        jLabel16.setText("Fecha producción");

        jLabel17.setText("No. cocinada");

        jLabel18.setText("Espec");

        jLabel19.setText("°Brix");

        jLabel20.setText("Ph");

        jLabel21.setText("Consistencia");

        jLabel22.setText("Apariencia");

        jLabel23.setText("Viscosidad");

        jLabel24.setText("Acidez");

        jLabel25.setText("Estatus FQ");

        jLabel26.setText("Estatus funcional");

        jLabel27.setText("Coliformes");

        jLabel28.setText("Cuenta estandar");

        jButton7.setText("Modify");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        f1.setBackground(new java.awt.Color(204, 204, 204));

        f2.setBackground(new java.awt.Color(204, 204, 204));
        f2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f2ActionPerformed(evt);
            }
        });

        f3.setBackground(new java.awt.Color(204, 204, 204));

        f4.setBackground(new java.awt.Color(204, 204, 204));

        f12.setBackground(new java.awt.Color(204, 204, 204));

        f13.setBackground(new java.awt.Color(204, 204, 204));

        f14.setBackground(new java.awt.Color(204, 204, 204));

        f15.setBackground(new java.awt.Color(204, 204, 204));

        f16.setBackground(new java.awt.Color(204, 204, 204));

        f17.setBackground(new java.awt.Color(204, 204, 204));

        f18.setBackground(new java.awt.Color(204, 204, 204));

        f20.setBackground(new java.awt.Color(204, 204, 204));

        f21.setBackground(new java.awt.Color(204, 204, 204));

        f7.setBackground(new java.awt.Color(204, 204, 204));

        f8.setBackground(new java.awt.Color(204, 204, 204));

        jLabel29.setText("Hongos");

        jLabel30.setText("Levaduras");

        jLabel31.setText("Estatus Micro");

        jLabel32.setText("Estatus Final");

        f9.setBackground(new java.awt.Color(204, 204, 204));

        f10.setBackground(new java.awt.Color(204, 204, 204));

        f11.setBackground(new java.awt.Color(204, 204, 204));

        f5.setBackground(new java.awt.Color(204, 204, 204));

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/logo.png"))); // NOI18N

        f6.setBackground(new java.awt.Color(204, 204, 204));

        jLabel49.setText("Operador");

        f19.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(f19);

        jLabel58.setText("Observaciones");

        javax.swing.GroupLayout modifyRTabLayout = new javax.swing.GroupLayout(modifyRTab);
        modifyRTab.setLayout(modifyRTabLayout);
        modifyRTabLayout.setHorizontalGroup(
            modifyRTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modifyRTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(modifyRTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modifyRTabLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(35, 35, 35)
                        .addComponent(upfield, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jButton6)
                        .addGap(36, 36, 36))
                    .addGroup(modifyRTabLayout.createSequentialGroup()
                        .addGroup(modifyRTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28))
                        .addGap(25, 25, 25)
                        .addGroup(modifyRTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(f1, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(f2)
                            .addComponent(f3)
                            .addComponent(f4)
                            .addComponent(f12)
                            .addComponent(f13)
                            .addComponent(f14)
                            .addComponent(f15)
                            .addComponent(f16)
                            .addComponent(f17)
                            .addComponent(f18)
                            .addComponent(f20)
                            .addComponent(f21)
                            .addComponent(f7)
                            .addComponent(f8))
                        .addGroup(modifyRTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modifyRTabLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton7)
                                .addGap(75, 75, 75))
                            .addGroup(modifyRTabLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(modifyRTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel54, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modifyRTabLayout.createSequentialGroup()
                                        .addGroup(modifyRTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel31)
                                            .addComponent(jLabel30)
                                            .addComponent(jLabel29)
                                            .addComponent(jLabel32)
                                            .addComponent(jLabel49))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(modifyRTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(f6)
                                            .addComponent(f9, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                            .addComponent(f10)
                                            .addComponent(f11)
                                            .addComponent(f5)))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(modifyRTabLayout.createSequentialGroup()
                                        .addComponent(jLabel58)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())))))
        );
        modifyRTabLayout.setVerticalGroup(
            modifyRTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modifyRTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(modifyRTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(upfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(modifyRTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(f1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(f9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(modifyRTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(f2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(f10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(modifyRTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(f3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(f11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(modifyRTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(f4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(f5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(modifyRTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(f12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel49))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(modifyRTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modifyRTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(f13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel58, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(modifyRTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(modifyRTabLayout.createSequentialGroup()
                        .addGroup(modifyRTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(f14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(modifyRTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(f15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(modifyRTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(f16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(modifyRTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(f17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(modifyRTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(f18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(modifyRTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(f20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(modifyRTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(f21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(modifyRTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(f7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(modifyRTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(f8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(modifyRTabLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel54)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        registerPane.addTab("Modify Register", modifyRTab);
        modifyRTab.getAccessibleContext().setAccessibleName("");

        jLabel33.setText("ID");

        delRegField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delRegFieldActionPerformed(evt);
            }
        });

        jButton8.setText("Delete");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/logo.png"))); // NOI18N

        javax.swing.GroupLayout eraseRTabLayout = new javax.swing.GroupLayout(eraseRTab);
        eraseRTab.setLayout(eraseRTabLayout);
        eraseRTabLayout.setHorizontalGroup(
            eraseRTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eraseRTabLayout.createSequentialGroup()
                .addGroup(eraseRTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(eraseRTabLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel33)
                        .addGap(18, 18, 18)
                        .addComponent(delRegField, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(eraseRTabLayout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jButton8)))
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eraseRTabLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel55)
                .addGap(18, 18, 18))
        );
        eraseRTabLayout.setVerticalGroup(
            eraseRTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eraseRTabLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(eraseRTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(delRegField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        registerPane.addTab("Erase Register", eraseRTab);

        javax.swing.GroupLayout regCtrlLayout = new javax.swing.GroupLayout(regCtrl);
        regCtrl.setLayout(regCtrlLayout);
        regCtrlLayout.setHorizontalGroup(
            regCtrlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerPane)
        );
        regCtrlLayout.setVerticalGroup(
            regCtrlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerPane)
        );

        registerPane.getAccessibleContext().setAccessibleName("");
        registerPane.getAccessibleContext().setAccessibleDescription("");

        controlPane.addTab("Register Control", regCtrl);

        jLabel34.setText("ID");

        jLabel35.setText("Parameter");

        a1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Brix", "Ph", "Consistencia", "Viscosidad", "Acidez" }));

        jLabel36.setText("Low Limit");

        jLabel37.setText("High Limit");

        jButton9.setText("Create");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel50.setText("-");

        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/logo.png"))); // NOI18N

        jLabel59.setText("Desciption");

        javax.swing.GroupLayout createATabLayout = new javax.swing.GroupLayout(createATab);
        createATab.setLayout(createATabLayout);
        createATabLayout.setHorizontalGroup(
            createATabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createATabLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(createATabLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(createATabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36)
                    .addGroup(createATabLayout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addGap(38, 38, 38)
                        .addComponent(alarmIDLb))
                    .addGroup(createATabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel59)
                        .addComponent(jLabel37)))
                .addGap(36, 36, 36)
                .addGroup(createATabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton9)
                    .addComponent(jLabel50)
                    .addComponent(a1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(createATabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(a4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(a2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                        .addComponent(a3, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        createATabLayout.setVerticalGroup(
            createATabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createATabLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(createATabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(alarmIDLb)
                    .addComponent(jLabel50))
                .addGap(29, 29, 29)
                .addGroup(createATabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(a1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createATabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(a2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createATabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(a3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createATabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel59)
                    .addComponent(a4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addGap(65, 65, 65)
                .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        alarmPane.addTab("Create Alarm", createATab);

        jLabel38.setText("ID");

        jButton10.setText("Search");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel39.setText("Parameter");

        jLabel40.setText("Low limit");

        jLabel41.setText("High limit");

        jLabel42.setText("Creation date");

        al1.setText("-");

        al2.setText("-");

        al3.setText("-");

        al4.setText("-");

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton11.setText("Erase");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/logo.png"))); // NOI18N

        javax.swing.GroupLayout eraseATabLayout = new javax.swing.GroupLayout(eraseATab);
        eraseATab.setLayout(eraseATabLayout);
        eraseATabLayout.setHorizontalGroup(
            eraseATabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eraseATabLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(eraseATabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(eraseATabLayout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addGap(35, 35, 35)
                        .addGroup(eraseATabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(eraseATabLayout.createSequentialGroup()
                                .addComponent(lookAlarm, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jButton10))
                            .addGroup(eraseATabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(eraseATabLayout.createSequentialGroup()
                                    .addComponent(jLabel42)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(al4))
                                .addGroup(eraseATabLayout.createSequentialGroup()
                                    .addComponent(jLabel41)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(al3))
                                .addGroup(eraseATabLayout.createSequentialGroup()
                                    .addComponent(jLabel40)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(al2))
                                .addGroup(eraseATabLayout.createSequentialGroup()
                                    .addComponent(jLabel39)
                                    .addGap(79, 79, 79)
                                    .addComponent(al1)))))
                    .addGroup(eraseATabLayout.createSequentialGroup()
                        .addComponent(jButton11)
                        .addGap(152, 152, 152)))
                .addContainerGap(117, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eraseATabLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel57)
                .addGap(19, 19, 19))
        );
        eraseATabLayout.setVerticalGroup(
            eraseATabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eraseATabLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(eraseATabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(lookAlarm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10))
                .addGap(49, 49, 49)
                .addGroup(eraseATabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(al1))
                .addGap(27, 27, 27)
                .addGroup(eraseATabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(al2))
                .addGap(29, 29, 29)
                .addGroup(eraseATabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(al3))
                .addGap(30, 30, 30)
                .addGroup(eraseATabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(al4))
                .addGap(18, 18, 18)
                .addComponent(jButton11)
                .addGap(53, 53, 53)
                .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        alarmPane.addTab("Erase Alarm", null, eraseATab, "");

        javax.swing.GroupLayout alarmCtrlLayout = new javax.swing.GroupLayout(alarmCtrl);
        alarmCtrl.setLayout(alarmCtrlLayout);
        alarmCtrlLayout.setHorizontalGroup(
            alarmCtrlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(alarmPane)
        );
        alarmCtrlLayout.setVerticalGroup(
            alarmCtrlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(alarmPane)
        );

        controlPane.addTab("Alarm Control", alarmCtrl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(controlPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(controlPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Muestra información de usuario:
        String [] ok = null;
        LogConexion conex = new LogConexion();
        conex.open();
        ok = conex.searchUser(Integer.parseInt(user_search_field.getText()));
        u_res_1.setText(ok[0]);
        u_res_4.setText(ok[1]);
        u_res_2.setText(ok[2]);
        u_res_3.setText(ok[3]);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void f2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // MODIFICA LA INFORMACIÓN DE LOS REGISTROS:
        int [] xtra = new int[2];
        int id = Integer.parseInt(upfield.getText());
        
        LogConexion upt = new LogConexion();
        upt.open();
        xtra = upt.getRegIds(id);
                //micros
        String m1 = f7.getText();
        String m2 = f8.getText();
        String m3 = f9.getText();
        String m4 = f10.getText();
        String m5 = f11.getText();
        int resp1 = upt.upMic(m1, m2, m3, m4, m5, id);
                //parameters
        String p1 = f12.getText();
        float p2 = Float.parseFloat(f13.getText());
        float p3 = Float.parseFloat(f14.getText());
        float p4 = Float.parseFloat(f15.getText());
        String p5 = f16.getText();
        float p6 = Float.parseFloat(f17.getText());
        float p7 = Float.parseFloat(f18.getText());
        String p8 = f19.getText();
        String p9 = f20.getText();
        String p10 = f21.getText();
        int resp2 = upt.upPar(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, xtra[0]);
                //registers
        String r1 = f1.getText();
        String r2 = f2.getText();
        String r3 = f3.getText();
        int r4 = Integer.parseInt(f4.getText());
        String r5 = f5.getText();
        String r6 = f6.getText();
        int resp3 = upt.upReg(r1, r2, r3, r4, r5, r6, xtra[1]);
        upt.close();
        
        if((resp1 != 0)&&(resp2 != 0)&&(resp3 != 0)){
            JOptionPane.showMessageDialog(this,"REGISTRO MODIFICADO",
                         "System",JOptionPane.PLAIN_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this,"NO MODIFICADO!!",
                         "System",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Modificador de usuarios
        int ok = 0;
        int id = Integer.parseInt(user_search_field.getText());
        String nik = u_res_1.getText();
        String pass = u_res_2.getText();
        String name = u_res_4.getText();
        int priv = Integer.parseInt(u_res_3.getText());
        
        LogConexion conex = new LogConexion();
        conex.open();
        ok = conex.changeUser(id, nik, name, pass, priv);
        conex.close();
        
        if(ok != 0){
            JOptionPane.showMessageDialog(this,"USUARIO MODIFICADO",
                         "System",JOptionPane.PLAIN_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this,"NO MODIFICADO!!",
                         "System",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Muestra usuario para eliminar:
        String [] ok = null;
        LogConexion conex = new LogConexion();
        conex.open();
        ok = conex.searchUser(Integer.parseInt(u_search_field.getText()));
        u_lb_1.setText(ok[0]);
        u_lb_2.setText(ok[3]);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void euser_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_euser_buttonActionPerformed
        //Kill de usuarios
        int ok = 0;
        int id = Integer.parseInt(u_search_field.getText());        
        LogConexion conex = new LogConexion();
        conex.open();
        ok = conex.deleUser(id);
        conex.close();
        
        if(ok != 0){
            JOptionPane.showMessageDialog(this,"USUARIO ELIMINADO",
                         "System",JOptionPane.PLAIN_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this,"NO ELIMINADO!!",
                         "System",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_euser_buttonActionPerformed

    private void cusr_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusr_buttonActionPerformed
        //Creador de nuevos usuarios
        int level = 1;
        int ok = 0;
        int id = 0;
        switch (cprivilegeCombo.getSelectedIndex()){
            case 0:
            level = 1;
            //System.out.println("CASO 0");
            break;
            case 1:
            level = 2;
            //System.out.println("CASO 1");
            break;
            case 2:
            level = 3;
            //System.out.println("CASO 2");
            break;
            default:
            //System.out.println("CASO DEFAULT");
            break;
        }
        LogConexion conex = new LogConexion();
        conex.open();
        ok = conex.addUser(cusernameField.getText(), cnamefield.getText(), cpasswordField.getText(), level);
        id = conex.getUId(cusernameField.getText());
        conex.close();
        user_etiqueta.setText(""+id);
        if(ok != 0){
            JOptionPane.showMessageDialog(this,"USUARIO CREADO",
                "System",JOptionPane.PLAIN_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this,"NO CREADO",
                "System",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_cusr_buttonActionPerformed

    private void cprivilegeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cprivilegeComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cprivilegeComboActionPerformed

    private void cusernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cusernameFieldActionPerformed

    private void u_res_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u_res_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_u_res_1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // Mostrar toda la info del registro:
        String [] datas = new String[21];
        LogConexion reg = new LogConexion();
        reg.open();
        int id = Integer.parseInt(upfield.getText());
        datas = reg.allRegister(id);
        reg.close();
        f1.setText(datas[0]);
        f2.setText(datas[1]);
        f3.setText(datas[2]);
        f4.setText(datas[3]);
        f5.setText(datas[4]);
        f6.setText(datas[5]);
        f7.setText(datas[6]);
        f8.setText(datas[7]);
        f9.setText(datas[8]);
        f10.setText(datas[9]);
        f11.setText(datas[10]);
        f12.setText(datas[11]);
        f13.setText(datas[12]);
        f14.setText(datas[13]);
        f15.setText(datas[14]);
        f16.setText(datas[15]);
        f17.setText(datas[16]);
        f18.setText(datas[17]);
        f19.setText(datas[18]);
        f20.setText(datas[19]);
        f21.setText(datas[20]);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // Borrar un registro:
        int id = Integer.parseInt(delRegField.getText());
        int [] xtra = new int[2];
        
        LogConexion del = new LogConexion();
        del.open();
        xtra = del.getRegIds(id);
        int result = del.deleReg(id, xtra[0], xtra[1]);
        del.close();
        
        if(result != 0){
            JOptionPane.showMessageDialog(this,"REGISTRO ELIMINADO!",
                "System",JOptionPane.PLAIN_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this,"ELIMINACIÓN FALLIDA...",
                "System",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void delRegFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delRegFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delRegFieldActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // Create alarm:
        String ca1 = a1.getSelectedItem().toString();
        float ca2 = Float.parseFloat(a2.getText());
        float ca3 = Float.parseFloat(a3.getText());
        String ca4 = a4.getText();
        int result = 0;
        
        LogConexion alm = new LogConexion();
        alm.open();
        result = alm.addAlarm(ca1, ca2, ca3, ca4);
        
        if(result != 0){
            JOptionPane.showMessageDialog(this,"ALARMA CREADA!!!",
                "System",JOptionPane.PLAIN_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this,"CREACION FALLIDA...",
                "System",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // despliega información de la alarma objetivo:
        int ida = Integer.parseInt(lookAlarm.getText());
        String [] xtra = new String[5];
        
        LogConexion sel = new LogConexion();
        sel.open();
        xtra = sel.searchAlarm(ida);
        al1.setText(xtra[0]);
        al2.setText(xtra[1]);
        al3.setText(xtra[2]);
        al4.setText(xtra[3]);
        sel.close();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        int ida = Integer.parseInt(lookAlarm.getText());
        LogConexion dal = new LogConexion();
        dal.open();
        int result = dal.alarmDele(ida);
        dal.close();
        if(result != 0){
            JOptionPane.showMessageDialog(this,"ALARMA ELIMINADA!!!",
                "System",JOptionPane.PLAIN_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this,"ELIMINACIÓN FALLIDA...",
                "System",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminSis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminSis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminSis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminSis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminSis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> a1;
    private javax.swing.JTextField a2;
    private javax.swing.JTextField a3;
    private javax.swing.JTextField a4;
    private javax.swing.JLabel al1;
    private javax.swing.JLabel al2;
    private javax.swing.JLabel al3;
    private javax.swing.JLabel al4;
    private javax.swing.JPanel alarmCtrl;
    private javax.swing.JLabel alarmIDLb;
    private javax.swing.JTabbedPane alarmPane;
    private javax.swing.JTextField cnamefield;
    private javax.swing.JTabbedPane controlPane;
    private javax.swing.JTextField cpasswordField;
    private javax.swing.JComboBox<String> cprivilegeCombo;
    private javax.swing.JPanel createATab;
    private javax.swing.JPanel createUTAb;
    private javax.swing.JTextField cusernameField;
    private javax.swing.JButton cusr_button;
    private javax.swing.JTextField delRegField;
    private javax.swing.JPanel eraseATab;
    private javax.swing.JPanel eraseRTab;
    private javax.swing.JPanel eraseUTab;
    private javax.swing.JButton euser_button;
    private javax.swing.JTextField f1;
    private javax.swing.JTextField f10;
    private javax.swing.JTextField f11;
    private javax.swing.JTextField f12;
    private javax.swing.JTextField f13;
    private javax.swing.JTextField f14;
    private javax.swing.JTextField f15;
    private javax.swing.JTextField f16;
    private javax.swing.JTextField f17;
    private javax.swing.JTextField f18;
    private javax.swing.JTextField f19;
    private javax.swing.JTextField f2;
    private javax.swing.JTextField f20;
    private javax.swing.JTextField f21;
    private javax.swing.JTextField f3;
    private javax.swing.JTextField f4;
    private javax.swing.JTextField f5;
    private javax.swing.JTextField f6;
    private javax.swing.JTextField f7;
    private javax.swing.JTextField f8;
    private javax.swing.JTextField f9;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lookAlarm;
    private javax.swing.JPanel modifyRTab;
    private javax.swing.JPanel modifyUTab;
    private javax.swing.JTabbedPane muser_button;
    private javax.swing.JLabel privilegeLb;
    private javax.swing.JPanel regCtrl;
    private javax.swing.JTabbedPane registerPane;
    private javax.swing.JLabel showNextID;
    private javax.swing.JLabel u_lb_1;
    private javax.swing.JLabel u_lb_2;
    private javax.swing.JTextField u_res_1;
    private javax.swing.JTextField u_res_2;
    private javax.swing.JTextField u_res_3;
    private javax.swing.JTextField u_res_4;
    private javax.swing.JTextField u_search_field;
    private javax.swing.JTextField upfield;
    private javax.swing.JPanel userCtrl;
    private javax.swing.JLabel user_etiqueta;
    private javax.swing.JTextField user_search_field;
    private javax.swing.JLabel usrLb;
    // End of variables declaration//GEN-END:variables
}
