package sistem;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Capital
 */
public class TaskManager extends javax.swing.JFrame {
    public String susuario;
    public int sid;
    /**
     * Creates new form TaskManager
     */
    public TaskManager() {
        initComponents();
        this.setLocationRelativeTo(null);
        pressLabel.setText("Bienvenido "+susuario);
    }
    
    public void setPrivileges(String level){
        switch (level){
            case "1":
                adminButton.setEnabled(false);
                staButton.setEnabled(false);
                reportButton.setEnabled(false);
                break;
            case "2":
                adminButton.setEnabled(false);
                break;
            case "3":
                capButton.setEnabled(false);
                staButton.setEnabled(false);
                reportButton.setEnabled(false);
                viewerButton.setEnabled(false);
                break;
            case "7":
                //modo absoluto
                break;
            default:
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminButton = new javax.swing.JButton();
        capButton = new javax.swing.JButton();
        staButton = new javax.swing.JButton();
        reportButton = new javax.swing.JButton();
        viewerButton = new javax.swing.JButton();
        levelLabel = new javax.swing.JLabel();
        pressLabel = new javax.swing.JLabel();
        pressLabel.setText("Bienvenido "+susuario);
        jScrollPane1 = new javax.swing.JScrollPane();
        alert_area = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        msg_dpl = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        msg_field = new javax.swing.JTextField();
        msg_button = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        act_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Task Manager");

        adminButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        adminButton.setText("Sys Admin");
        adminButton.setToolTipText("Control total del sistema");
        adminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonActionPerformed(evt);
            }
        });

        capButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        capButton.setText("Capture");
        capButton.setToolTipText("Captura registro ");
        capButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capButtonActionPerformed(evt);
            }
        });

        staButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        staButton.setText("Stadistics");
        staButton.setToolTipText("Generación de estadisticas por fecha");
        staButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staButtonActionPerformed(evt);
            }
        });

        reportButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        reportButton.setText("Report ");
        reportButton.setToolTipText("Generación de reporte: necesario el ID del estadistico generado.");
        reportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportButtonActionPerformed(evt);
            }
        });

        viewerButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        viewerButton.setText("Viewer");
        viewerButton.setToolTipText("Visualizador de registros");
        viewerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewerButtonActionPerformed(evt);
            }
        });

        levelLabel.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        levelLabel.setText("-");
        levelLabel.setToolTipText("");

        pressLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pressLabel.setText("-");

        alert_area.setEditable(false);
        alert_area.setBackground(new java.awt.Color(240, 240, 240));
        alert_area.setColumns(20);
        alert_area.setForeground(new java.awt.Color(153, 0, 51));
        alert_area.setRows(5);
        jScrollPane1.setViewportView(alert_area);
        String dato = "";
        LogConexion dos = new LogConexion();
        dos.open();
        dato = dos.gAlarmOn();
        dos.close();
        alert_area.setText(dato);

        msg_dpl.setEditable(false);
        msg_dpl.setBackground(new java.awt.Color(240, 240, 240));
        msg_dpl.setColumns(20);
        msg_dpl.setRows(5);
        jScrollPane2.setViewportView(msg_dpl);
        String data = "";
        LogConexion dis = new LogConexion();
        dis.open();
        data = dis.gMensage();
        dis.close();
        msg_dpl.setText(data);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Recados:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Alertas:");

        msg_button.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        msg_button.setText("Enviar");
        msg_button.setToolTipText("Envia un recado a visualizarpor todos los usuarios");
        msg_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msg_buttonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(java.awt.Color.black);
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 4, true));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel1)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        act_button.setText("Actualizar");
        act_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                act_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(staButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(capButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(act_button))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(msg_field)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(levelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(msg_button)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(pressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(capButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pressLabel)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(act_button)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(viewerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(staButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(adminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(msg_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(msg_button))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(levelLabel))
        );

        pressLabel.setText("Bienvenido "+susuario);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportButtonActionPerformed
        Reporter repo = new Reporter();
        repo.setCurrentUser(susuario, sid);
        repo.setVisible(true);
    }//GEN-LAST:event_reportButtonActionPerformed

    private void capButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capButtonActionPerformed
        Capture_2 capt = new Capture_2();
        capt.setCurrentUser(susuario, sid);
        capt.setVisible(true);   
    }//GEN-LAST:event_capButtonActionPerformed

    private void adminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonActionPerformed
        AdminSis adm = new AdminSis();
        adm.setCurrentUser(susuario, sid);
        adm.setVisible(true);   
    }//GEN-LAST:event_adminButtonActionPerformed

    private void staButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staButtonActionPerformed
        Stadistic sta = new Stadistic();
        sta.setCurrentUser(susuario, sid);
        sta.setVisible(true);
    }//GEN-LAST:event_staButtonActionPerformed

    private void viewerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewerButtonActionPerformed
        Viewer vie = new Viewer();
        vie.setVisible(true);
    }//GEN-LAST:event_viewerButtonActionPerformed

    private void msg_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msg_buttonActionPerformed
        // Grabar mensages:
        String data = "";
        String msg = msg_field.getText();
        if(!msg.isEmpty()){
            LogConexion men = new LogConexion();
            men.open();
            men.sMensage(msg, sid);
            data =  men.gMensage();
            msg_dpl.setText(data);
            men.close();
        }
    }//GEN-LAST:event_msg_buttonActionPerformed

    private void act_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_act_buttonActionPerformed
        String da = "";
        LogConexion di = new LogConexion();
        di.open();
        da = di.gAlarmOn();
        di.close();
        alert_area.setText(da);
    }//GEN-LAST:event_act_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaskManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaskManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaskManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaskManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaskManager().setVisible(true);
            }
        });
        
        
    }
    
    public void setCurrentUser(String name, int id){
        this.susuario = name;
        this.sid = id;
        pressLabel.setText("Bienvenido "+name);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton act_button;
    private javax.swing.JButton adminButton;
    private javax.swing.JTextArea alert_area;
    private javax.swing.JButton capButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JLabel levelLabel;
    private javax.swing.JButton msg_button;
    private javax.swing.JTextArea msg_dpl;
    private javax.swing.JTextField msg_field;
    public javax.swing.JLabel pressLabel;
    private javax.swing.JButton reportButton;
    private javax.swing.JButton staButton;
    private javax.swing.JButton viewerButton;
    // End of variables declaration//GEN-END:variables

}
